import hmac
import hashlib
import json
import re

# Secret key used to verify signatures between the satellite network gateway and your system node
# In production, this would be managed securely via an environment variable or secret manager
SHARED_MCC_SECRET = b"CospasSarsatOperationalSecretKey2026!"

def verify_packet_authentication(payload_bytes: bytes, received_signature: str) -> bool:
    """
    Verifies that the incoming message packet was generated by an authorized 
    satellite terminal by checking its HMAC-SHA256 digital signature matrix.
    """
    if not received_signature:
        return False
        
    # Generate the expected cryptographic signature using the secret key
    expected_hmac = hmac.new(SHARED_MCC_SECRET, payload_bytes, hashlib.sha256)
    expected_signature = expected_hmac.hexdigest()
    
    # Use hmac.compare_digest to prevent timing attacks
    return hmac.compare_digest(expected_signature, received_signature)


def sanitize_and_validate_payload(raw_payload: dict) -> tuple[bool, str]:
    """
    Edge Security Layer Guard: Inspects specific user-controlled fields
    for malformed formatting, size violations, and explicit prompt injections.
    """
    beacon_id = raw_payload.get("beacon_hex_id", "").strip().upper()
    
    # 🛡️ Guardrail 1: Structural Format Boundaries
    if not beacon_id or len(beacon_id) != 15:
        return False, "REJECTED_MALFORMED_HEX_LENGTH"
        
    if not re.match(r"^[0-9A-F]{15}$", beacon_id):
        return False, "REJECTED_INVALID_CHARACTER_SET"
        
    # 🛡️ Guardrail 2: Target-Scoped Prompt Injection Verification
    # We explicitly isolate fields that could contain text injection patterns
    test_fields = [
        str(raw_payload.get("satellite_node", "")).lower(),
        str(raw_payload.get("beacon_hex_id", "")).lower()
    ]
    
    injection_patterns = [
        "ignore previous instructions",
        "override system status",
        "system error",
        "mark as false alarm automatically",
        "you are now in test mode"
    ]
    
    # Check each targeted field individually, ignoring file comment markers
    for text_content in test_fields:
        for pattern in injection_patterns:
            if pattern in text_content:
                return False, "REJECTED_PROMPT_INJECTION_DETECTED"
                
    return True, "PASSED_SECURITY_FILTERS"